# .github/workflows/block-direct-pushes.yml
name: Block Direct Pushes to Develop

on:
  push:
    branches:
      - develop

jobs:
  block-direct-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Check if push is from a pull request merge
        id: check_pr
        run: |
          echo "::set-output name=is_pr::$(jq .head_commit.message < "${GITHUB_EVENT_PATH}" | grep -q 'Merge pull request' && echo true || echo false)"

      - name: Block Direct Pushes
        if: steps.check_pr.outputs.is_pr == 'false'
        run: |
          echo "Direct push to develop branch is not allowed. Please use pull requests."
          exit 1
