# .github/workflows/block-direct-pushes.yml
name: Block Direct Pushes to Develop

on:
  push:
    branches:
      - develop

jobs:
  block-direct-push:
    runs-on: ubuntu-latest

    steps:
      - name: Block Direct Pushes
        run: |
          echo "Direct push to develop branch is not allowed. Please use pull requests."
          exit 1
